#!/bin/bash
#
read -p "Please enter your service name: " service_name
read -p  "Do you want to check the status of your service name (Please enter yes or no): " status_check

if [ $status_check == yes ]; then
	systemctl status $service_name | grep -w "active"
	echo "The service is active"
elif [ $status_check == yes ]; then
	systemctl status $service_name | grep -w "inactive"
	echo "The service is not working"
else
	echo "Skipped"
fi


